services:
  db_pg_16:
    image: postgres:16
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox_user
      POSTGRES_PASSWORD: sandbox_password
    ports:
      - 5432
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  site:
    build: .
    depends_on:
      - db_pg_16
    networks:
      ipv4host:
        ipv4_address: 192.168.1.6
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_pg_16:5432/sandbox
      SPRING_DATASOURCE_USERNAME: sandbox_user
      SPRING_DATASOURCE_PASSWORD: sandbox_password
volumes:
  db:
networks:
  ipv4host:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24