services:
  db_pg_16:
    image: postgres:16
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox_user
      POSTGRES_PASSWORD: sandbox_password
    ports:
      - 5432
  site:
    build: .
    depends_on:
      - db_pg_16
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/sandbox
      SPRING_DATASOURCE_USERNAME: sandbox_user
      SPRING_DATASOURCE_PASSWORD: sandbox_password
volumes:
  db: