
services:
  db_pg_16:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: sandbox
      POSTGRES_USER: sandbox_user
      POSTGRES_PASSWORD: sandbox_password
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db:/data/postgres/data
    networks:
      dockerlocal:


  site:
    build: ./site_docker/.
    depends_on:
      - db_pg_16
    networks:
      dockerlocal:
      ipv4host:
        ipv4_address: 192.168.1.6
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_pg_16:5432/sandbox
      SPRING_DATASOURCE_USERNAME: sandbox_user
      SPRING_DATASOURCE_PASSWORD: sandbox_password
volumes:
  db:
networks:
  dockerlocal:
    driver: bridge
  ipv4host:
    ipam:
      driver: host
      config:
        - subnet: 192.168.1.0/24