server:
  port: 8080
  address: 

spring:
  datasource:
    url: jdbc:postgresql://db_pg_16:5432/sandbox
    username: sandbox_user
    password: sandbox_password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  docker:
    compose:
      enabled: true
      skip:
        in-tests: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
